### ISSUE TITLE
Accessing `$validationAttributeNames` from `Validator::replace`?

### ISSUE THREAD

**Issue by jordanlev** [dwightwatson/validating#134]
I am providing some custom validation rules in my AppServiceProvider, and also some calls to `Validator::replace` so I can modify the error message placeholders for those custom rules. However, I'm not sure how to have that function figure out which model is being validated so I can determine the proper `$validationAttributeName` for the given field name.

For example, in my model file I have this:
```
use ValidatingTrait;
protected $rules = [
	'starts_on' => 'required|date',
	'ends_on' => 'required|date|on_or_after:starts_on',
];
protected $validationAttributeNames = [
	'starts_on' => 'Starts On Date',
	'ends_on' => 'Ends On Date',
];
```

And in my AppServiceProvider.php file's `boot()` method I have this:
```
Validator::extend('on_or_after', function ($attribute, $value, $parameters) {
	return strtotime(Input::get($parameters[0])) <= strtotime($value);
});

Validator::replacer('on_or_after', function($message, $attribute, $rule, $parameters) {
	$field_name = $parameters[0];

	//HERE IS WHERE I HAVE THE PROBLEM:
	// Somehow I need to access the model that is currently being validated
	// and call `getValidationAttributeNames()` on it so I can retrieve the human-readable
	// name for the $field_name key.
	$field_label = ???;

	return str_replace(':date', $field_label, $message);
});
```

_(Note that the ":date" placeholder is there because I have this: `'on_or_after' => ':attribute must be on or after :date',` set in my resources/lang/en/validation.php array)_

Thanks for any guidance you can provide (and thanks for all the great work on this module -- it's exactly what I was looking for, coming from the Rails world).

**Comment by dwightwatson** [comment]
I was under the impression that you could set custom attribute names in your translation file as well, under the `attributes` key of the validation translation file. Of course this means they would be shared across all validators, self-validating models or otherwise, so this may or may not work for your use case.

Unfortunately I don't think there would be a way to access the model under validation cleanly in the replacer as the validator is completely unaware of the context it is being used in. 

I hope this helps, sorry I don't have an easy solution for you!
