### ISSUE TITLE
Question: Using model factories for models with validating trait

### ISSUE THREAD

**Issue by tristangodfrey** [dwightwatson/validating#140]
Imagine a user class which utilises the validating trait, the following will not work because of validation logic being executed and coming back with an error:

```
factory(App\User::class)->create()
```

Obviously I can't call `forceSave` on the factory class, so is there a workaround for this? Thanks in advance.

**Comment by dalabarge** [comment]
@tristangodfrey you might want to consider using:

```php
$user = factory(App\User::class)->make();
$user->setValidating(false);
$user->save();
```

Or define a custom factory that generates values that match your validation logic.

@dwightwatson we might want to consider building a factory trait that does this automatically so that instead of using the default factory in Laravel you could use this custom one that turns off validating.

**Comment by tristangodfrey** [comment]
@dalabarge Thanks for your response. One more question, what if I want to do this when creating related models eg (laravel docs example):
```
$users = factory(App\User::class, 3)
           ->create()
           ->each(function($u) {
                $u->posts()->save(factory(App\Post::class)->make());
            });
```

Post would have a validation rule that checks for `user_id`

Is there a solution for this too?

**Comment by dalabarge** [comment]
@tristangodfrey you could of course just pass in your custom rules when you save things such as:

```php
$rules = ['user_id' => 'required|exists:users,id'];
$users = factory(App\User::class, 3)
           ->create()
           ->each(function($user) use ($rules) {
                 $post = factory(App\Post::class)->make();
                 $post->setRules($rules);
                 $user->posts()->save($post);
            });
```

I'd suggest you take a gander at the public methods of the validating trait to understand what methods are at your disposal for creating the functionality you want. It may be ugly and lengthy right now but if you start finding some patterns in your work you could submit a PR for a more elegant solution which @dwightwatson would probably accept. One such solution might be to use Proxies or Decorators for the underlying models which make the changes to the model for validation purposes at the moment they are saved vs. being configured by this factory method before hand.

Another possible solution is to use http://github.com/esensi/model which is an abstraction of this package with some extra traits tossed in. One of the features dropped from this package has been backported in esensi/model and that is the use of rulesets which allow for this behavior without having to modify the factory methods. That said those backported features are also deprecated and will be removed in a future version so it might be best to rely on a more forward thinking solution.

**Comment by dwightwatson** [comment]
I don't really understand the use case for saving an invalid model - if your factory definition describes a valid model then it shouldn't have a problem saving it to the database. Likewise, assuming your factory definitions were valid I don't see why you would have any issue persisting an associated model, Laravel would set the foreign key for you.

If you really did want to persist an invalid model from a factory you can do it in one line...

    factory(App\User::class)->create()->forceSave();

If you've got any ideas on how to improve the workflow for testing I'm all ears, and any PRs would be appreciated. I don't think disabling model validation in tests is the right approach because then you're not testing how your app actually works, but I'm sure there are other thoughts on this.

**Comment by tristangodfrey** [comment]
@dwightwatson @dalabarge Massive apologies for wasting your time, but my issue was being caused by a mistake I made myself. I actually thought that when I was using my model factories to persist models to the database, the validating trait was kicking in and stopping me from saving them. This however was an incorrect assumption, the mistake I actually made was not differentiating between `save` and `saveMany`. :disappointed: 

I failed to properly read the error message and surely after some code modification everything worked just fine.

@dwightwatson I agree that there isn't really a good reason to disable model validation, even for testing. Couldn't really think of any use cases myself either. If however there is anything I can do to contribute in any way feel free to let me know, I feel I owe you both one.

Thanks for your time and once again apologies for wasting it.
