### ISSUE TITLE
Tag new version for Laravel 5.2

### ISSUE THREAD

**Issue by Propaganistas** [dwightwatson/validating#150]
Hi

I see you committed an update to `composer.json` to support Laravel 5.2

Could you please tag a new version so it can be installed without pointing to a specific commit or `dev-master`?

Thanks.

**Comment by dwightwatson** [comment]
I've just pushed a new release which supports Laravel 5.1.27+ and 5.2.0+. This introduces the breaking change to `saveOrFail` which now used a method provided by the framework. For this reason I used a new major version, `2.0.0`.

Older versions of the framework should continue to use `1.0.*`, and I think the way I've configured the `composer.json` file will allow for this automatically.

**Comment by dwightwatson** [comment]
Turns out that didn't work as well as I'd have liked, it wasn't playing along with Laravel 5.1.27 at all. I'll try and get around to getting this tagged shortly, Christmas has been keeping me busy. If you've got any idea how to sort the `composer.json` issue with both streams of Laravel I'm happy to bring in a PR.

**Comment by dwightwatson** [comment]
I think I've got it this time - `2.0.0` has been tagged!
