### ISSUE TITLE
User model validation

### ISSUE THREAD

**Issue by snipe** [dwightwatson/validating#152]
Hi there! First off, thanks so much for this package. It makes validation in Laravel SO much easier. I just wish I had found it a few projects ago. 

![1236537281_the_it_crowd](https://cloud.githubusercontent.com/assets/197404/12370212/efacac84-bbbc-11e5-9daa-a603707cc39c.gif)

I have a question on best implementation. A password is required at the User model level, but I obviously don't want to require them to enter their password every time they update their profile. Is the suggestion to leave password out of the User model, and instead use Laravel 5.2's form request stuff? I'm not sure how that would work with this package, but then I haven't dug too far into that feature in Laravel 5+ yet.

Thanks so much in advance!

**Comment by dwightwatson** [comment]
Thanks!

Hm, I don't think there's a best approach as such, but I'll mention how I used to go about it. It's important to remember that this package isn't validating the *request*, but just the state the model is in after you've updated it with the request input. Because of this, it's not required that the user provide the password every time they update their profile.

The way I used to use it was to have `'password' => 'required'` on my User model. If you wanted to go nuts, you could specify that the size was 40 characters, or however long the password has is. I'd also have this sort of mutator:

    public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = bcrypt($value);
    }

I hope this makes sense, in the way that you don't need the password on every update, just that the update doesn't remove a password. If you wanted to add want to add additional validation on a profile update (for say, a minimum length of a password) you could use a FormRequest, though I'd probably just use the `$this->validates($request, [...])` method.

[Here's the last commit of my blog back when it was on Laravel 4.2](https://github.com/dwightwatson/neontsunami/tree/85ed06524e834999678ff92bbab520d17ce17889), and used this library (I moved to FormRequests with Laravel 5.0). It's old code, but it might give some more insight into how to use the library. But again none of this 'best approach', rather just the way I did it.

I hope this helps!
