### ISSUE TITLE
_token field causing problems with fill()

### ISSUE THREAD

**Issue by johnmackenzie91** [dwightwatson/validating#164]
Hey Guys I am passing the request parameters straight into the newly created object but sadly the _token variable for CSRF is causing problems, is the currently a way around this?

$organisation = new Organisation();

if($organisation->create($request::all())){ << MassAssignmentException
}

Thanks

**Comment by dwightwatson** [comment]
Mass assignment is something that is managed by Eloquent, and it requires you to set `$fillable` on your model to define what attributes can be set on your model. For example, you wouldn't have `_token` set on your model, so you wouldn't include it in the `$fillable` array. For more information on mass assignment, [read the Laravel documentation on it](https://laravel.com/docs/5.2/eloquent#mass-assignment).

Totally unrelated, but if you're injecting the request into your method, you should call `$request->all()`, rather than calling it statically (with `::`).

**Comment by dalabarge** [comment]
@johnmackenzie91 you can also take a little at the sister project github.com/esensi/model which has auto-purging for such autofills which can be useful for when you need to fill a field that will be mutated and validated against but should be purged after the fact just before save. That said, @dwightwatson is right, you shouldn't have unwanted `$fillable` keys and/or should consider using form request validation if the property does not exist on the model.
