### ISSUE TITLE
Rules should be on the Validating trait

### ISSUE THREAD

**Issue by RomanDeNu** [dwightwatson/validating#166]
If you leave the rules property off your model, Laravel assumes it's a relationship then fails due to the relationship not existing.  If you were to put the rules property onto the ValidatingTrait defaulted to an empty array.  Laravel wouldn't throw the error stating Rules is not a relationship.

**Comment by dwightwatson** [comment]
Don't really understand the issue here... don't use the trait if you're not providing rules for the model to validate with? I don't believe we can set the property to be an empty array on the trait without it throwing an error when the property is redefined on the model (otherwise it probably would have been done already).

**Comment by dalabarge** [comment]
And to clarify, if you extend the `ValidatingModel` you get the `$rules = []` for free.
