### ISSUE TITLE
Exception isn't thrown with 5.3

### ISSUE THREAD

**Issue by pratyushbarik** [dwightwatson/validating#169]
Currently `Watson\Validating\ValidationException` extends `Illuminate\Contracts\Validation\ValidationException`. But as of Laravel 5.3 `Illuminate\Contracts\Validation\ValidationException` doesn't exist.

A quick fix is to change `Illuminate\Contracts\Validation\ValidationException` to `Illuminate\Validation\ValidationException`. But I am not sure whether this is a solution or just a workaround.

**Comment by dwightwatson** [comment]
Looks like this is the go - Laravel no longer has a validation exception contract, so we should be able to just extend the concrete class instead. I've pushed this fix to `master` if you'd like to try it out, otherwise I'll probably tag a new release this afternoon.

**Comment by pratyushbarik** [comment]
Thank you. Maybe a new dev branch to keep compatibility until we find a solution.

**Comment by dwightwatson** [comment]
Alright - I've branched off the existing stuff to `2.x` as I think we're going to need a new major version to support Laravel 5.3. 

The `ValidationException` contract we used to extend from has since been removed, so we'll need to flip to extend the concrete `ValidationException`. It has a different interface, and it's also used by the framework's exception handler. This means, when a `ValidationException` is left uncaught, Laravel will redirect back to the previous page with the errors - like a `FormRequest` works.

This is all sitting on `master` now, I'll leave it a little to actually give it a good test. If you have time, please give it a run as well. Once I'm comfortable I'll push out `3.0.0` for Laravel 5.3

**Comment by pratyushbarik** [comment]
Yeah. I am going to use this with Laravel 5.3 on production so testing it out. I have changed the base exception class to `ValidationException` and using it currently. I haven't run into any errors yet. Though I am just using it as a REST API backend.
I can see the version 2.2 on packagist, but composer update doesn't update the package. My `composer.json` has the version set to `^2.2`. Any idea on that?

**Comment by dwightwatson** [comment]
You'll need to flip your constraint to "dev-master" to pull in the latest code, as it's untagged. A little more has changed under the hood than just changing the base exception, but it should still work just the same.

**Comment by dwightwatson** [comment]
Tagged `3.0.0` as this should be good to go. Please let me know if you run into any other issues!
