### ISSUE TITLE
checking for $myModel->rules when non-existent causes LogicException

### ISSUE THREAD

**Issue by tmaly1980** [dwightwatson/validating#171]
If the rules instance variable doesn't exist on a model (such as when I don't want any), I get a LogicException, as Eloquent looks for a method named 'rules' due to it's relation handling. It assumes any method named after an accessor is going to be a relation. Unfortunately, THIS module (ValidatingTrait) has a 'rules()' method, which confuses Eloquent, and it throws this error:

LogicException with message 'Relationship method must return an object of type Illuminate\Database\Eloquent\Relations\Relation'

Realistically, the method should be called differently from the attribute, so it doesn't cause this exception, ie 'getRules()' instead of rules. Most of eloquent does that sort of behavior. Getters have "get" in the name. 

I'm noticing that there's already a getRules() so the rules() method ought to be removed immediately.

Otherwise, it needs to be documented that not declaring $rules will trigger an exception, trying to establish a relationship with incompatible data. Realistically though I think the method should be removed.

**Comment by dwightwatson** [comment]
I would have thought if you didn't want any validation, you simply wouldn't include the trait on your model. If you needed to include the trait for whatever reason but didn't want to perform validation then worst case is setting an empty array as your ruleset.

Looking at the [protected `rules()` method](https://github.com/dwightwatson/validating/blob/master/src/ValidatingTrait.php#L196-L205) it seems as though it was added as a shorthand to a model's rules by calling `Model::rules()`. The `getRules()` method instead is meant to be called on a model instance.

I'm happy to accept a PR if you want to add a notice that not declaring `$rules` would throw an exception. I never thought noting that was necessary as all the documentation indicates that the property is required and the use of the library without it doesn't make sense.

**Comment by tmaly1980** [comment]
The issue is I put my trait in a core model I inherit from every other
model... Regardless the issue isn't clear why I get a logic exception. I
don't think naming a method theis good design either way.

**Comment by dwightwatson** [comment]
Cool, I understand where you're coming from. Easiest fix there would be to place an empty ruleset on your base model.

You're getting a logic exception because you're using the package in a way that wasn't intended... I'm not sure it's feasible that it throws a custom specific exception for each invalid use case.

I'm not going to argue over method naming, not all Eloquent methods are prefixed with get/set and it's not something that can be changed easily without breaking backwards compatibility.

Like I said, I'm happy to bring in more documentation that explains the error for anyone that receives it, but I honestly don't think it's that common.

**Comment by tmaly1980** [comment]
It looks like ValidatingTrait::rules() simply calls ValidatingTrait::getRules(), so I don't see why we even need rules() except for convenience. But mentioning it in the documentation sounds like an adequate solution otherwise. If the trait is used but the rules are not declared (or empty), then it's not very helpful about the LogicException, what that means and what to do to fix it. Eloquent was designed to interpret methods named after accessors as relationships, so isset($this->rules) ends up calling getAttribute() on rules() and tries to apply that as a relationship, hence the exception. Solutions should be obvious to problems, but that's just my philosophy. If we can at least agree upon adding directly to the documentation that omitting the $rules list may throw an exception, that's good enough.

**Comment by dwightwatson** [comment]
`rules()` literally is just there for convenience. I think there was a request for it much earlier on, I don't remember exactly how it came to be. 

I've added a note to the documentation that includes the full exception message so that if anyone else runs into the issue they would be able to find the solution easily. Let me know if you think this would do the trick or if something more is required.
