### ISSUE TITLE
Validation does not fire on model->creating()

### ISSUE THREAD

**Issue by deonvdv** [dwightwatson/validating#175]
I was playing with various validation scenarios and found that validation only fires on saving and restoring. I have used model->create quite a bit in my tests, so firing the validation on `creating` would be appreciated. Tx

**Comment by dwightwatson** [comment]
Validation is meant to fire on `creating`. Would you be able to provide some sample code that demonstrates what you're doing and how it isn't working?

**Comment by deonvdv** [comment]
sure @dwightwatson 

I have a Client class with the following rules:

```
    protected $rules = [
        'name' => 'required|between:3,255',
        'slug' => 'required|between:3,60',
    ];

```
And I am testing it in a phpunit test with the following:

```
        $this->assertFalse(\App\Client::create([
                                                   'name' => 'X',
                                               ]));

```
I am expecting the create to fail due to name being too short and slug not being present.

I also have the following test:

```
        $client = \App\Client::create([
                                           'name' => 'X',
                                       ]);
        $this->assertFalse($client->isValid());

```
I hope this helps.

**Comment by deonvdv** [comment]
@dwightwatson - I just noticed that validation does run on create() but it does not stop the creating process. For save(), it returns false if it cannot save, but for create() it returns the model with validation errors.

**Comment by dwightwatson** [comment]
Have you definitely included the trait with the class? Are you using any other packages or libraries that could interfere with validation or event handling from occurring? Which version of Laravel are you using, and which version of this package?

I've just created a fresh Laravel project and it's all working as expected. Here's the user model:

```
<?php

namespace App;

use Watson\Validating\ValidatingTrait;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use ValidatingTrait, Notifiable;

    protected $rules = [
        'name' => 'required|min:5',
        'email' => 'required'
    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}
```

And here's the output from my console as I tested it:

```
>>> $user = App\User::create(['name' => 'Foo']);
=> App\User {#684
     name: "Foo",
   }
>>> $user->isValid();
=> false
>>> $user->getErrors()->all();
=> [
     "The name must be at least 5 characters.",
     "The email field is required.",
   ]
>>> $user->exists;
=> false
>>> App\User::count();
=> 0
```

**Comment by dwightwatson** [comment]
Wait, are you confusing the fact a model is returned with it being persisted or not?

**Comment by deonvdv** [comment]
@dwightwatson - I was expecting a false result since validation failed. I seldom use the create() outside of unit tests.

I am using Laravel 5.3.24. I have a BaseModel class that Client inherits from. The ValidatingTrait is included in the base model.

If the return of the model on create() is the desired outcome, then please ignore this and we can close the issue. It just felt intuitive to expect a false like I get on save(). Am I making sense?

**Comment by dwightwatson** [comment]
Ah, I'm with you now. What you're saying makes total sense.

I can see *why* one might expect `create()` to return `false` if validation fails - it certainly reads as though that should be the case. However it wouldn't give you much of a chance to get the validation errors if this was the case. 

I think it's been Laravel convention as well that `create()` would return the model instance while `save()` would return a boolean indicating whether it was successful or not, which is why it was a good method to override for validation.

I think the options for your use case would be to a) check the model is valid after creating it and then handle it as necessary or b) enable validation exceptions, so that when you do call `create()` and validation fails an exception is thrown - which you can either catch yourself and handle as normal or allow Laravel to handle as a normal validation exception.

I hope this makes sense and I'm sorry it took a little longer to get on the same page. Let me know if there is anything else I can do to help.

**Comment by deonvdv** [comment]
tx for looking into this @dwightwatson. Appreciate it.

Taking your recommendation "a" works well.

```
        $client = \App\Client::create([
                                           'name' => 'X',
                                       ]);
        $this->assertFalse($client->isValid());

```
Tx
