### ISSUE TITLE
Suggestion: Static accessors for attribute names and messages

### ISSUE THREAD

**Issue by SirLamer** [dwightwatson/validating#182]
The model properties "$validationAttributeNames" and "$validationMessages" should be made static and then provided static getter methods.

One of the potential benefits of this package is the ability to centralize validation rules which are being used in multiple spaces. In my case, I have a JSON API and I also have POST form submissions, and finally this package is useful for validating models right before save to protect from programming errors introducing bad data structures.

When validating a form or API submission before populating the model, it is useful to have static accessors. For the moment, I am instancing a new Model, then calling these methods non-statically and discarding the instanced Model. This is somewhat inefficient.

Example of current implementation within a Form Request:
```php
    public function messages()
    {
        return (new Project())->getValidationMessages();
    }
```

Example of preferred technique:
```php
    public function messages()
    {
        return Project::getValidationMessages();
    }
```

Further to this, I would argue that the same approach to $rules should also be followed except I am aware of a past issue ticket where this was decided against.
https://github.com/dwightwatson/validating/issues/59

I am not aware of a good reason for making changes to the validation rules on the fly. This seems like sloppy design and also seems like a security hole. In the case where this is really needed, the designer can validate the data external to the model using a copy of the "$rules" with adjustment as needed, then commit changes to the Model using a save action with validation bypassed/disabled. Making these validation properties non-static and editable on every Model instance is also a waste of memory and has a small I/O performance impact since every since instance of a Model in memory will has its own unique copy of these rules.

I know Laravel makes it easy and fun to call non-static methods via static Facade helpers and the like, however I feel like this feature gets abused a little bit within the Laravel community.

**Comment by dwightwatson** [comment]
It's unlikely that we're going to make `$rules` a static property. It's been this way since day one and while the ability to change rules on the fly isn't as much as a core feature as it once was I don't think it's worth making the change.

I'm happy to look at PR that adds static accessors to access validation rules and messages if that's something you'd find useful, even if it just does `(new static)->getValidationMessages()` sort of thing.

**Comment by SirLamer** [comment]
Another way to provide dynamic assignment would be to a separate private property on the trait for storage of runtime validation inputs, then during validation it could merge the on-model default $rules property with the runtime custom one. This could allow the application designer to just add rules for the instance. It would then also allow proper static access to the configuration on the model, and reduce the I/O and memory use in most cases.

**Comment by dwightwatson** [comment]
I've had to rename these methods so that they wouldn't conflict with Eloquent, They're now called `::modelValidationMessages` and `::modelValidationAttributeNames`. It does make them inconsistent with the rules helper, so I may add a `::modelRules` method as well just for completion's sake. Tagged in `3.1.1`.
