### ISSUE TITLE
laravel 5.5

### ISSUE THREAD

**Issue by dwenaus** [dwightwatson/validating#192]
is this package required now that validation has native support in laravel 5.5?

**Comment by dwightwatson** [comment]
Validation has been in Laravel for as long as I can remember.

Form request validation came in Laravel 5.0 from memory.

This library is for self validating models - models that can only be saved if they are considered valid - very Rails-esque. Otherwise generally with Laravel you will be validating your request input instead. Pick the approach that works better for you.
