### ISSUE TITLE
Add custom error to Model

### ISSUE THREAD

**Issue by avasiliev87** [dwightwatson/validating#206]
Is it possible to add custom validation error to model? something like following.

`if (!$video->published()){ $video->addError('notification', 'can be sent for only published videos') }`

**Comment by dwightwatson** [comment]
You could use `setErrors` to manually set the error bag, I suppose in this instance you would want to get the error bag, append to it and set it again. However, it's not something I'd be looking to support normally. For your example, it sounds more like something that would be handled by a policy rather than validation.
