### ISSUE TITLE
Just a note regarding the readme.md

### ISSUE THREAD

**Issue by chriskonnertz** [dwightwatson/validating#213]
Just a note: it is a bit irritating that when you come to the repo here on GitHub and scroll down you see "Laravel 5.3" in the `Readme.md` from the `master` branch. 

In the `3.2.0` tag it has been changed to `Laravel 5.3+` - it would be nice to see this in the `master` branch as well so it appears when landing here. :bulb:

**Comment by dwightwatson** [comment]
I am... really confused. I was looking into this to see what the deal was - because I was sure that change was on the master branch - but then it just seemed to refresh and show up! 

 I did wonder if I should update it to 5.3-5.8 just to show that it's still compatible with the latest and greatest as well, but that would require updating it each time. Don't know if it would matter.

Anyway, thanks for the heads up!

**Comment by chriskonnertz** [comment]
Okay, now it is there... Nice! 

In my opinion "5.3+" is fine.
