### ISSUE TITLE
Issue with Laravel 7.x custom Casts and validation

### ISSUE THREAD

**Issue by Mechstud** [dwightwatson/validating#222]
Hi, there seems to be an issue with Laravel 7.x providing custom Casts feature: https://laravel.com/docs/7.x/eloquent-mutators#custom-casts

I defined a custom Cast, for eg: `ZoneEnum`, which implements `CastsAttributes` interface. Eg: North, South, East and West And in the `get()` method of this, I return an object of `ZoneEnum`, based on the value stored in the database. While setting the attribute, I mutate from a `ZoneEnum` object to its string value, in the `set()` method implementation.

The problem here is that in the ```getModelAttributes()``` function (refer: https://github.com/dwightwatson/validating/blob/master/src/ValidatingTrait.php#L131),  you are getting attribute values utilizing the Accessor logic. This makes Laravel's code cast the (already mutated/set) value back to `ZoneEnum` object. This then fails the validation logic.

Also, I noticed that `getAttributes()` function alone should be enough; you dont really need to mutate again using `getAttributeValue()`, unless I am missing something ?

_Originally posted by @Mechstud in https://github.com/dwightwatson/validating/pull/221#issuecomment-596195754_

**Comment by dwightwatson** [comment]
Just been taking a look at this. I don't remember the original context, but it looks like we pass the mutated/cast values into the validator (with the exception of date casts - because the date validators don't know how to deal with Carbon instances). I believe the intention was that you should be validating a model "as-is" rather than the raw attributes underneath.

I've taken a look at writing the code to have the raw underlying values of a custom cast passed into the validator, but this introduces an inconsistency with existing casts. I don't think it makes sense that the validator gets the cast value of an "out of the box" caster, but gets the raw value of a "custom" caster.

Perhaps your validations need to be updated to work with the cast value rather than the original, but I can see how that's less than ideal. However, I think that's part of the compromise of doing model validations when the framework has leaned heavily toward request validations.

I hope this makes sense, but as it stands now this is expected behaviour and unlikely to change.

**Comment by Mechstud** [comment]
In that case, just like with date values can't be handled because of Carbon
instances; you will need to modify the code to ignore Custom Casts as well
(added in Laravel 7.x). Because Custom Casts can also return an object
instead of string values (validator can work with primitive types only)

**Comment by dwightwatson** [comment]
An exception was made for Carbon instances, but not for other casts - all other casts are applied, and so are custom casts.

**Comment by Mechstud** [comment]
Thanks for the response. This comment is for any other, using the library, and facing similar issue with Custom Casts in Laravel 7.x, can utilize my fix. In my Base Model class, I overrided the `getModelAttributes()` function to use `getAttributes()` only. As, in Laravel 6+ (afaik), it is already mutated using **set mutators**. Here is a code snippet:

```
use Watson\Validating\ValidatingModel;

abstract class BaseModel extends ValidatingModel
{
    /**
     * @overload
     */
    public function getModelAttributes()
    {
        return $this->getAttributes();
    }
}
```
