### ISSUE TITLE
Lost Laravel 6 support

### ISSUE THREAD

**Issue by Cyrille37** [dwightwatson/validating#227]
Hello

U brought Laravel 6 support with e4204622726b0d6cbfa4a301743fc31e033df5cd but at [tag 6.0](https://github.com/dwightwatson/validating/commits/6.0.0) it has been erased by followed commits 679cb805bb8a342956045fd3f7bacba1a01ae860 (        "illuminate/validation": "~7.0") then 51296a70e755caf5907d947570f28fc738de413c ("illuminate/validation": "~8.0").

So I could not find a way to **install watson/validating for Laravel 6 LTS**. Have I miss something ?

Thanks & cheers.

related: #218

**Comment by dwightwatson** [comment]
The more recent versions have dropped support for Laravel 6.0, but you can continue to use the version that just. It looks like `watson/validating` version `4.0.0` is the version you'll need to install to use alongside Laravel 6.0. I don't believe there is much that has changed functionality wise since that version - just bumps to support different versions of Laravel. Hope this helps!

**Comment by Cyrille37** [comment]
Thanks! version 4.0.0 do the job :-)
